#-------------------------------
# EVENTS
#-------------------------------
#EVENTO DE PASO A DESARROLLO
.event_dev:
  only:
    refs:
      - /^feature/
  except:
    variables:
      - $CI_COMMIT_TITLE =~ /^WIP:/

#EVENTO DE PASO A DESARROLLO MR
.event_dev_mr:
  only:
    refs:
      - merge_requests
    variables:
      - $CI_COMMIT_REF_NAME =~ /^feature/

#EVENTO DE PASO A STAGING
.event_staging:
  only:
    refs:
      - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^chore/

#EVENTO DE PASO A PROD
.event_prod:
  only:
    refs:
      - tags
