.install_cache:
  cache:
    key: $CI_PROJECT_ID
    paths:
      - ./node_modules
      - ./.next/cache/
      - ./.yarn-cache
    policy: pull-push

#BEFORE SCRIPT
.install_before_script:
  before_script:

#AFTER SCRIPT
.install_after_script:
  after_script:

#SCRIPT
.install_script:
  script:
    - >
      if [ "$NPM_INSTALL" = "true" ]; then
        npm config set cache /cache/npm --global
        npm install
      else
        yarn config set cache-folder /cache/.yarn-cache 
        yarn install
      fi

#TAGS
.install_tags:
  tags: []

#-------------------------------
# BASE
#-------------------------------
.install:
  image: node:14-alpine
  stage: install
  extends:
    - .install_tags
    - .install_before_script
    - .install_script
    - .install_after_script
    - .install_cache
  variables:
    NPM_INSTALL: 'false'
  allow_failure: false

#-------------------------------
# EVENTS
#-------------------------------
.event_dev: {}
.event_dev_mr: {}
.event_staging: {}
.event_prod: {}

#-------------------------------
# JOBS
#-------------------------------
install:feature:dev:
  extends:
    - .install
    - .event_dev
  environment:
    name: Dev
  when: manual

install:feature:dev:mr:
  extends:
    - .install
    - .event_dev_mr
  environment:
    name: Dev
  when: manual

install:feature:staging:
  extends:
    - .install
    - .event_staging
  environment:
    name: Staging

install:prod:
  extends:
    - .install
    - .event_prod
  environment:
    name: Prod
