.lint_cache:
  cache:
    key: $CI_PROJECT_ID
    paths:
      - ./node_modules
      - ./.next/cache/
      - ./.yarn-cache
    policy: pull

#BEFORE SCRIPT
.lint_before_script:
  before_script:

#AFTER SCRIPT
.lint_after_script:
  after_script:

#SCRIPT
.lint_test_script:
  script:
    - >
      if [ "$NPM_INSTALL" = "true" ]; then
        npm config set cache /cache/npm --global
        npm run test:lint
      else
        yarn config set cache-folder /cache/.yarn-cache 
        yarn run test:lint
      fi

#ARTIFACTS
.lint_artifacts:
  artifacts:
    when: always
    expire_in: 2 yr
    paths:
      - public/

#TAGS
.lint_tags:
  tags: []

#-------------------------------
# BASE
#-------------------------------
.lint:
  image: node:14-alpine
  stage: test
  extends:
    - .lint_tags
    - .lint_before_script
    - .lint_test_script
    - .lint_after_script
    - .lint_cache
    - .lint_artifacts
  allow_failure: true

#-------------------------------
# EVENTS
#-------------------------------
.event_dev: {}
.event_dev_mr: {}
.event_staging: {}
.event_prod: {}

#-------------------------------
# JOBS
#-------------------------------
test:lint:feature:dev:
  extends:
    - .lint
    - .event_dev
  variables:
    STAGE: dev

test:lint:feature:dev:mr:
  extends:
    - .lint
    - .event_dev_mr
  variables:
    STAGE: dev

test:lint:feature:staging:
  extends:
    - .lint
    - .event_staging
  variables:
    STAGE: staging

test:lint:prod:
  extends:
    - .lint
    - .event_prod
  variables:
    STAGE: prod
