export const USER_IMG_DEFAULT = 'https://bit.ly/broken-link';
export const EMAIL_DOMAIN = '@tested.cl';
export const COGNITO_AUTH_ERRORS = {
  userPoolId: 'no_valid_user_pool_id',
  emailDomain: 'no_valid_user_email_domain',
  userGroup: 'no_valid_user_group',
};
export const LOGIN_AUTH_ERRORS = {
  userPoolId: 'Tu cuenta no es válida o no está autorizada',
  emailDomain: 'Tu cuenta no es válida',
  userGroup: 'Tu cuenta no está autorizada, comunicate con administración',
};
export const MONTH_NAMES = [
  'Ene',
  'Feb',
  'Mar',
  'Abr',
  'May',
  'Jun',
  'Jul',
  'Ago',
  'Sep',
  'Oct',
  'Nov',
  'Dic',
];
export const DAY_NAMES = ['Dom', 'Lun', 'Mar', 'Mier', 'Jue', 'Vie', 'Sab'];

export type SchedulesT = 'domicilio-covid' | 'domicilio-core' | 'utm-covid' | 'utm-core';
type ScheduleConf = {
  id: SchedulesT;
  title: string;
  isLab: boolean;
  isCovid: boolean;
};

export const BOOKING_SCHEDULES: Record<SchedulesT, ScheduleConf> = {
  'domicilio-covid': {
    id: 'domicilio-covid',
    title: 'Domicilio COVID',
    isLab: false,
    isCovid: true,
  },
  'domicilio-core': {
    id: 'domicilio-core',
    title: 'Domicilio CORE',
    isLab: false,
    isCovid: false,
  },
  'utm-covid': {
    id: 'utm-covid',
    title: 'UTM COVID',
    isLab: true,
    isCovid: true,
  },
  'utm-core': { id: 'utm-core', title: 'UTM CORE', isLab: true, isCovid: false },
};

export const ORDER_REPORT_TYPE = {
  'domicilio-covid': {
    id: 'domicilio-covid',
    title: 'Domicilio COVID',
    isLab: false,
    isCovid: true,
    owner: 'Metropolitana',
  },
  'domicilio-core': {
    id: 'domicilio-core',
    title: 'Domicilio CORE',
    isLab: false,
    isCovid: false,
    owner: 'Metropolitana',
  },
  'valparaiso-covid': {
    id: 'valparaiso-covid',
    title: 'Valparaíso COVID',
    isLab: false,
    isCovid: true,
    owner: 'Valparaíso',
  },
  'valparaiso-core': {
    id: 'valparaiso-core',
    title: 'Valparaíso CORE',
    isLab: false,
    isCovid: false,
    owner: 'Valparaíso',
  },
  'utm-covid': {
    id: 'utm-covid',
    title: 'UTM COVID',
    isLab: true,
    isCovid: true,
    owner: 'UTM',
  },
  'utm-core': {
    id: 'utm-core',
    title: 'UTM CORE',
    isLab: true,
    isCovid: false,
    owner: 'UTM',
  },
};

export const XLSX_HEADER: LooseObject = {
  simpliRoute: [
    { key: 'name', tittle: 'Título' },
    { key: 'direction', tittle: 'Dirección completa' },
    { key: 'charge', tittle: 'Carga' },
    { key: 'startTime', tittle: 'Hora Inicial' },
    { key: 'endTime', tittle: 'Hora Final' },
    { key: 'timeService', tittle: 'Tiempo de Servicio' },
    { key: 'notes', tittle: 'Notas' },
    { key: 'lat', tittle: 'Latitud' },
    { key: 'long', tittle: 'Longitud' },
    { key: 'id', tittle: 'Id de referencia' },
    { key: 'requiredSkills', tittle: 'Habilidades requeridas' },
    { key: 'operationalSkills', tittle: 'Habilidades operacionales' },
    { key: 'contactPerson', tittle: 'Persona de contacto' },
    { key: 'phone', tittle: 'Télefono de contacto' },
    { key: 'startTime2', tittle: 'Hora inicial 2' },
    { key: 'endTime2', tittle: 'Hora final 2' },
    { key: 'charge2', tittle: 'Carga 2' },
    { key: 'charge3', tittle: 'Carga 3' },
    { key: 'priority', tittle: 'Prioridad' },
    { key: 'sms', tittle: 'SMS' },
    { key: 'email', tittle: 'Correo electrónico de contacto' },
    { key: 'chargePick', tittle: 'Carga pick' },
    { key: 'chargePick2', tittle: 'Carga pick 2' },
    { key: 'chargePick3', tittle: 'Carga pick 3' },
    { key: 'typeVisit', tittle: 'Tipo de visita' },
  ],
  novuslis: [
    // { key: 'orderNumber', tittle: 'N° Orden' },
    { key: 'code', tittle: 'CODIGOINSUMO' },
    { key: 'rut', tittle: 'RUT' },
    { key: 'dv', tittle: 'DV' },
    { key: 'passport', tittle: 'PASAPORTE' },
    { key: 'name', tittle: 'NOMBRES' },
    { key: 'lastName', tittle: 'APELLIDO PATERNO' },
    { key: 'secondLastName', tittle: 'APELLIDO MATERNO' },
    { key: 'birthdate', tittle: 'FECHA NACIMIENTO' },
    { key: 'gender', tittle: 'SEXO' },
    { key: 'direction', tittle: 'DIRECCION' },
    { key: 'state', tittle: 'COMUNA' },
    { key: 'phone', tittle: 'TELEFONO' },
    { key: 'email', tittle: 'E-MAIL' },
    { key: 'office', tittle: 'SUCURSAL/CLIENTE' },
    { key: 'procedence', tittle: 'PROCEDENCIA' },
    { key: 'agreement', tittle: 'CONVENIO' },
    { key: 'benefit', tittle: 'PRESTACION' },
  ],
  allOrders: [
    { key: 'orderNumber', tittle: 'N ORDEN' },
    { key: 'orderState', tittle: 'ESTADO ORDEN' },
    { key: 'paymentMethod', tittle: 'METODO PAGO' },
    { key: 'amount', tittle: 'PAGO TOTAL' },
    { key: 'paymentDate', tittle: 'FECHA DE PAGO' },
    { key: 'status', tittle: 'ESTADO PAGO' },
    { key: 'rut', tittle: 'RUT' },
    { key: 'passport', tittle: 'PASAPORTE' },
    { key: 'name', tittle: 'NOMBRES' },
    { key: 'lastName', tittle: 'APELLIDO PATERNO' },
    { key: 'secondLastName', tittle: 'APELLIDO MATERNO' },
    { key: 'birthdate', tittle: 'FECHA NACIMIENTO' },
    { key: 'gender', tittle: 'GENERO' },
    { key: 'address', tittle: 'DIRECCION' },
    { key: 'addressNumber', tittle: 'NUMERO DOMICILIO' },
    { key: 'addressDetail', tittle: 'DIRECCION DETALLE' },
    { key: 'province', tittle: 'REGION' },
    { key: 'stateName', tittle: 'COMUNA' },
    { key: 'phone', tittle: 'TELEFONO' },
    { key: 'email', tittle: 'E-MAIL' },
    { key: 'testReason', tittle: 'RAZON DEL TEST' },
    { key: 'date', tittle: 'FECHA AGENDADA' },
    { key: 'start', tittle: 'H. INICIO' },
    { key: 'end', tittle: 'H. FIN' },
    { key: 'title', tittle: 'EXAMEN' },
    { key: 'code', tittle: 'CODIGO EXAMEN' },
    { key: 'isCovid', tittle: 'ES COVID' },
    { key: 'isLab', tittle: 'ES UTM' },
    { key: 'isFast', tittle: 'ES AYUNO' },
  ],
  softland: [
    { key: 'Tipo_de_Documento_de_Venta', tittle: 'Tipo_de_Documento_de_Venta' },
    { key: 'code', tittle: 'Subtipo_del_Documento' },
    { key: 'code', tittle: 'Estado_del_Documento' },
    { key: 'code', tittle: 'Bodega_Origen_de_los_Productos' },
    { key: 'code', tittle: 'Numero_de_Documento' },
    { key: 'code', tittle: 'Fecha_de_Generacion_del_Documento' },
    { key: 'code', tittle: 'Concepto_del_Documento' },
    { key: 'code', tittle: 'Fecha_de_Vencimiento_del_Documento' },
    { key: 'code', tittle: 'Observacion' },
    { key: 'code', tittle: 'Moneda_del_Documento' },
    { key: 'code', tittle: 'Equivalencia_de_la_Moneda_de_Venta_del_Documento' },
    { key: 'code', tittle: 'NCredito_por_Devolucion_o_Refacturacion' },
    { key: 'code', tittle: 'Guia_de_Entrada_que_Referencia' },
    { key: 'code', tittle: 'Motivo_Anulacion' },
    { key: 'code', tittle: 'Nro_Documento_que_Referencia' },
    { key: 'code', tittle: 'Tipo_de_documento_que_referencia' },
    { key: 'code', tittle: 'Codigo_de_Cliente' },
    { key: 'code', tittle: 'Nombre_del_Cliente' },
    { key: 'code', tittle: 'Rut_del_Cliente' },
    { key: 'code', tittle: 'Giro_del_Cliente' },
    { key: 'code', tittle: 'Mail_DTE_del_Cliente' },
    { key: 'code', tittle: 'Direccion_del_Cliente' },
    { key: 'code', tittle: 'N_Direccion_del_Cliente' },
    { key: 'code', tittle: 'Comuna_del_Cliente' },
    { key: 'code', tittle: 'Ciudad_del_Cliente' },
    { key: 'code', tittle: 'Lugar_del_Documento' },
    { key: 'code', tittle: 'Direccion_del_Documento' },
    { key: 'code', tittle: 'Codigo_Comuna_del_Documento' },
    { key: 'code', tittle: 'Codigo_Ciudad_del_Documento' },
    { key: 'code', tittle: 'Codigo_Region_del_Documento' },
    { key: 'code', tittle: 'Codigo_Pais_del_Documento' },
    { key: 'code', tittle: 'Codigo_Lista_de_Precios' },
    { key: 'code', tittle: 'Codigo_de_Vendedor' },
    { key: 'code', tittle: 'Codigo_Centro_de_Costo' },
    { key: 'code', tittle: 'Codigo_Condicion_de_Pago' },
    { key: 'code', tittle: 'Codigo_de_Distribuidor' },
    { key: 'code', tittle: 'Nombre_de_Distribuidor' },
    { key: 'code', tittle: 'Codigo_Lugar_de_Despacho' },
    { key: 'code', tittle: 'Retirado_Por' },
    { key: 'code', tittle: 'Patente_del_Camion_de_Despacho' },
    { key: 'code', tittle: 'Solicitado_Por' },
    { key: 'code', tittle: 'Rut_Solicitante' },
    { key: 'code', tittle: 'Despachado_Por' },
    { key: 'code', tittle: 'Rut_Transportista' },
    { key: 'code', tittle: 'Cuenta_Contable_para_Notas_de_Debito' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_1' },
    { key: 'code', tittle: 'Valor_de_Descuento_1' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_2' },
    { key: 'code', tittle: 'Valor_de_Descuento_2' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_3' },
    { key: 'code', tittle: 'Valor_de_Descuento_3' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_4' },
    { key: 'code', tittle: 'Valor_de_Descuento_4' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_5' },
    { key: 'code', tittle: 'Valor_de_Descuento_5' },
    { key: 'code', tittle: 'Flete' },
    { key: 'code', tittle: 'Embalaje' },
    { key: 'code', tittle: 'Codigo_de_Canal_de_Ventas' },
    { key: 'code', tittle: 'Total_Final' },
    { key: 'code', tittle: 'Codigo_de_Producto' },
    { key: 'code', tittle: 'Codigo_Unidad_de_Medida' },
    { key: 'code', tittle: 'Detalle_del_Producto' },
    { key: 'code', tittle: 'Descripcion_del_Producto' },
    { key: 'code', tittle: 'Cantidad_Facturada' },
    { key: 'code', tittle: 'Cantidad_Despachada' },
    { key: 'code', tittle: 'Precio_Unitario_Moneda_Base' },
    { key: 'code', tittle: 'Precio_Unitario_Moneda_de_Venta' },
    { key: 'code', tittle: 'Equivalencia_de_la_moneda_del_producto_vs_base' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_de_Linea_1' },
    { key: 'code', tittle: 'Valor_de_Descuento_de_Linea_1' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_de_Linea_2' },
    { key: 'code', tittle: 'Valor_de_Descuento_de_Linea_2' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_de_Linea_3' },
    { key: 'code', tittle: 'Valor_de_Descuento_de_Linea_3' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_de_Linea_4' },
    { key: 'code', tittle: 'Valor_de_Descuento_de_Linea_4' },
    { key: 'code', tittle: 'Porcentaje_de_Descuento_de_Linea_5' },
    { key: 'code', tittle: 'Valor_de_Descuento_de_Linea_5' },
    { key: 'code', tittle: 'Valor_Total_Descuentos_de_Linea' },
    { key: 'code', tittle: 'Porcentaje_de_credito_Empresas_Constructoras' },
    { key: 'code', tittle: 'Valor_Total_de_Credito_Empresas_Constructoras' },
    { key: 'code', tittle: 'Partida_o_Talla' },
    { key: 'code', tittle: 'Pieza_o_Color' },
    { key: 'code', tittle: 'Fecha_de_Vencimiento_de_la_Partida_o_Pieza' },
    { key: 'code', tittle: 'Serie' },
    { key: 'code', tittle: 'Numero_Nota_de_Venta' },
    { key: 'code', tittle: 'Identificador_Impresora_Fiscal' },
    { key: 'code', tittle: 'Conserva_Folio_Asignado_al_DTE' },
    { key: 'code', tittle: 'Referencia_1_Tipo_Documento_SII' },
    { key: 'code', tittle: 'Referencia_1_Descripcion' },
    { key: 'code', tittle: 'Referencia_1_Numero_Documento' },
    { key: 'code', tittle: 'Referencia_1_Fecha_Documento' },
    { key: 'code', tittle: 'Referencia_1_Codigo_Referencia_Boleta' },
    { key: 'code', tittle: 'Referencia_2_Tipo_Documento_SII' },
    { key: 'code', tittle: 'Referencia_2_Descripcion' },
    { key: 'code', tittle: 'Referencia_2_Numero_Documento' },
    { key: 'code', tittle: 'Referencia_2_Fecha_Documento' },
    { key: 'code', tittle: 'Referencia_2_Codigo_Referencia_Boleta' },
    { key: 'code', tittle: 'Referencia_3_Tipo_Documento_SII' },
    { key: 'code', tittle: 'Referencia_3_Descripcion' },
    { key: 'code', tittle: 'Referencia_3_Numero_Documento' },
    { key: 'code', tittle: 'Referencia_3_Fecha_Documento' },
    { key: 'code', tittle: 'Referencia_3_Codigo_Referencia_Boleta' },
    { key: 'code', tittle: 'Referencia_4_Tipo_Documento_SII' },
    { key: 'code', tittle: 'Referencia_4_Descripcion' },
    { key: 'code', tittle: 'Referencia_4_Numero_Documento' },
    { key: 'code', tittle: 'Referencia_4_Fecha_Documento' },
    { key: 'code', tittle: 'Referencia_4_Codigo_Referencia_Boleta' },
    { key: 'code', tittle: 'Referencia_5_Tipo_Documento_SII' },
    { key: 'code', tittle: 'Referencia_5_Descripcion' },
    { key: 'code', tittle: 'Referencia_5_Numero_Documento' },
    { key: 'code', tittle: 'Referencia_5_Fecha_Documento' },
    { key: 'code', tittle: 'Referencia_5_Codigo_Referencia_Boleta' },
    { key: 'code', tittle: 'Tipo_de_Transaccion' },
    { key: 'code', tittle: 'Forma_Pago_SII' },
    { key: 'code', tittle: 'ExportacionIndicador_de_Servicio' },
    { key: 'code', tittle: 'ExportacionForma_de_Pago_Exportacion' },
    { key: 'code', tittle: 'ExportacionIdAdicional_Receptor_Extranjero' },
    { key: 'code', tittle: 'ExportacionRut_Chofer' },
    { key: 'code', tittle: 'ExportacionNombre_Chofer' },
    { key: 'code', tittle: 'ExportacionModalidad_de_Venta' },
    { key: 'code', tittle: 'ExportacionClausula_de_Exportacion' },
    { key: 'code', tittle: 'ExportacionTotal_Clausula_de_Ventas_Exportacion' },
    { key: 'code', tittle: 'ExportacionRecargo_sTotal_Clausula_de_Venta' },
    { key: 'code', tittle: 'ExportacionVia_de_Transporte' },
    { key: 'code', tittle: 'ExportacionIddel_Medio_de_Transporte' },
    { key: 'code', tittle: 'ExportacionRut_Compania_Transportista' },
    { key: 'code', tittle: 'ExportacionNombre_Compania_Transportadora' },
    { key: 'code', tittle: 'ExportacionIdAdicional_Cia_Transportadora' },
    { key: 'code', tittle: 'ExportacionBooking' },
    { key: 'code', tittle: 'ExportacionMotoNave' },
    { key: 'code', tittle: 'ExportacionCodigo_de_Operador' },
    { key: 'code', tittle: 'ExportacionPuerto_de_Embarque' },
    { key: 'code', tittle: 'ExportacionIdAdicional_Puerto_de_Embarque' },
    { key: 'code', tittle: 'ExportacionPuerto_de_Desembarque' },
    { key: 'code', tittle: 'ExportacionIdAdicional_Puerto_de_Desembarque' },
    { key: 'code', tittle: 'ExportacionTara' },
    { key: 'code', tittle: 'ExportacionUnidad_de_Medida_Tara' },
    { key: 'code', tittle: 'ExportacionTotal_Peso_Bruto' },
    { key: 'code', tittle: 'ExportacionUnidad_Peso_Bruto' },
    { key: 'code', tittle: 'ExportacionTotal_Peso_Neto' },
    { key: 'code', tittle: 'ExportacionUnidad_Peso_Neto' },
    { key: 'code', tittle: 'ExportacionTotal_Items' },
    { key: 'code', tittle: 'ExportacionTotal_Bultos' },
    { key: 'code', tittle: 'ExportacionTipo_de_Bulto' },
    { key: 'code', tittle: 'ExportacionMarca' },
    { key: 'code', tittle: 'ExportacionId_Container' },
    { key: 'code', tittle: 'ExportacionSello' },
    { key: 'code', tittle: 'ExportacionEmisor_Sello' },
    { key: 'code', tittle: 'ExportacionFlete' },
    { key: 'code', tittle: 'ExportacionSeguro' },
    { key: 'code', tittle: 'ExportacionCodigo_Pais_Receptor' },
    { key: 'code', tittle: 'ExportacionTipo_Moneda_Transaccion' },
  ],
};

export const OPERATION_TABLE_COLUMNS = {
  orderNumber: { label: 'N° Orden', style: { width: 110 } },
  orderState: { label: 'Estado', style: { width: 100 } },
  paymentDate: { label: 'Fecha de pago', style: { width: 190 } },
  amount: { label: 'Pago Total', style: { width: 110 } },
  total: { label: 'Personas', style: { width: 110 } },
  paymentMethod: { label: 'Medio de pago', style: { width: 140 } },
  title: { label: 'Examen', style: { width: 264 } },
  date: { label: ' Fecha agendada', style: { width: 164 } },
  start: { label: 'H. inicio', style: { width: 100 } },
  end: { label: 'H. termino' },
  rut: { label: 'RUT' },
  passport: { label: 'Pasaporte' },
  name: { label: 'Nombre', style: { width: 164 } },
  lastName: { label: '1er Apellido', style: { width: 164 } },
  secondLastName: { label: '2do Apellido', style: { width: 132 } },
  phone: { label: 'Teléfono' },
  email: { label: 'Email', style: { width: 220 } },
  gender: { label: 'Género' },
  birthdate: { label: 'F. Nacimiento', style: { width: 140 } },
  province: { label: 'Región' },
  stateName: { label: 'Comuna' },
  address: { label: 'Domicilio', style: { width: 264 } },
  addressNumber: { label: 'N° Domicilio' },
  code: { label: 'Cod. examen' },
  isCovid: { label: 'Es Covid', style: { width: 105 } },
  isFast: { label: 'Es Ayuno', style: { width: 105 } },
  isLab: { label: 'En UTM', style: { width: 105 } },
  testReason: { label: 'Razón del test', style: { width: 280 } },
};

export const CUSTOMER_SERVICE_TABLE_COLUMNS = {
  orderNumber: { label: 'N° Orden', style: { width: 110 } },
  orderState: { label: 'Estado', style: { width: 100 } },
  paymentDate: { label: 'Fecha de pago', style: { width: 190 } },
  amount: { label: 'Pago Total', style: { width: 110 } },
  total: { label: 'Personas', style: { width: 110 } },
  paymentMethod: { label: 'Medio de pago', style: { width: 140 } },
  title: { label: 'Examen', style: { width: 264 } },
  date: { label: ' Fecha agendada', style: { width: 164 } },
  start: { label: 'H. inicio', style: { width: 100 } },
  end: { label: 'H. termino' },
  rut: { label: 'RUT' },
  passport: { label: 'Pasaporte' },
  name: { label: 'Nombre', style: { width: 164 } },
  lastName: { label: '1er Apellido', style: { width: 164 } },
  secondLastName: { label: '2do Apellido', style: { width: 132 } },
  phone: { label: 'Teléfono' },
  email: { label: 'Email', style: { width: 220 } },
  province: { label: 'Región' },
  stateName: { label: 'Comuna' },
  address: { label: 'Domicilio', style: { width: 264 } },
  addressNumber: { label: 'N° Domicilio' },
  code: { label: 'Cod. examen' },
  isCovid: { label: 'Es Covid', style: { width: 105 } },
  isFast: { label: 'Es Ayuno', style: { width: 105 } },
  isLab: { label: 'En UTM', style: { width: 105 } },
};
