export const mockTableData = [
  {
    order_id: 1,
    order_number: '8783124212',
    person_name: 'Alfredo',
    email: 'akleinert0@telegraph.co.uk',
    gender: 'Genderfluid',
    payment_date: '6/29/2021',
    order_total: '97',
    persons_amount: 1,
    test_reason: 'Abrasion, right great toe, sequela',
    booking_date: '5/25/2021',
    booking_time: '1:40 PM',
    id_number: '48744835-C',
    passport: 'TOM986584',
    phone: '5912723847',
    billing_address: '77770 Bunker Hill Terrace',
    billing_address2: 'Tomscot',
    booking_resource: null,
    birth_date: '2/16/1981',
    product_name: 'S90411S',
    payment_method: 'Zoombox',
    comune: 'Blagoevgrad',
  },
  {
    order_id: 2,
    order_number: '3554574703',
    person_name: 'Si',
    email: 'sconnop1@usa.gov',
    gender: 'Genderfluid',
    payment_date: '6/18/2021',
    order_total: '1',
    persons_amount: 2,
    test_reason: 'Poisoning by antithyroid drugs, assault, initial encounter',
    booking_date: '9/15/2020',
    booking_time: '8:17 AM',
    id_number: '53615979-J',
    passport: 'NYX535756',
    phone: '7916410101',
    billing_address: '822 Knutson Plaza',
    billing_address2: 'Basil',
    booking_resource: null,
    birth_date: '2/27/1990',
    product_name: 'T382X3A',
    payment_method: 'Jabberbean',
    comune: 'Pithoro',
  },
  {
    order_id: 3,
    order_number: '0519623152',
    person_name: 'Bob',
    email: 'bharmant2@sohu.com',
    gender: 'Genderfluid',
    payment_date: '2/24/2021',
    order_total: '83',
    persons_amount: 4,
    test_reason: 'Open bite of left eyelid and periocular area, sequela',
    booking_date: '8/1/2021',
    booking_time: '2:34 PM',
    id_number: '92476731-6',
    passport: 'DJV656792',
    phone: '1758043510',
    billing_address: '2 Fieldstone Crossing',
    billing_address2: 'Division',
    booking_resource: null,
    birth_date: '12/1/1982',
    product_name: 'S01152S',
    payment_method: 'Ntags',
    comune: 'Calomboyan',
  },
  {
    order_id: 4,
    order_number: '0030634128',
    person_name: 'Tynan',
    email: 'tfideler3@vistaprint.com',
    gender: 'Genderqueer',
    payment_date: '4/23/2021',
    order_total: '97',
    persons_amount: 5,
    test_reason: 'Nondisp fx of triquetrum bone, r wrs, 7thD',
    booking_date: '8/30/2020',
    booking_time: '11:16 AM',
    id_number: '83935637-D',
    passport: 'WLM842438',
    phone: '4435130952',
    billing_address: '2889 Di Loreto Point',
    billing_address2: 'Old Gate',
    booking_resource: null,
    birth_date: '10/2/1993',
    product_name: 'S62114D',
    payment_method: 'Riffpath',
    comune: 'Jianshe',
  },
  {
    order_id: 5,
    order_number: '0175297895',
    person_name: 'Tricia',
    email: 'tlamswood4@nymag.com',
    gender: 'Polygender',
    payment_date: '12/26/2020',
    order_total: '19',
    persons_amount: 4,
    test_reason: 'Other injury of transverse colon',
    booking_date: '7/12/2021',
    booking_time: '2:33 PM',
    id_number: '98022561-D',
    passport: null,
    phone: '8896187098',
    billing_address: '6426 Dunning Way',
    billing_address2: 'Macpherson',
    booking_resource: null,
    birth_date: '1/1/1981',
    product_name: 'S36591',
    payment_method: 'Realpoint',
    comune: 'Sala',
  },
  {
    order_id: 6,
    order_number: '5193025706',
    person_name: 'Correna',
    email: 'ctoner5@bing.com',
    gender: 'Bigender',
    payment_date: '2/27/2021',
    order_total: '115',
    persons_amount: 5,
    test_reason: 'Kitchen in apartment as place',
    booking_date: '6/29/2021',
    booking_time: '11:10 AM',
    id_number: '90651409-S',
    passport: 'LEQ971260',
    phone: '1105777480',
    billing_address: '4 Eastlawn Hill',
    billing_address2: 'Forest Dale',
    booking_resource: null,
    birth_date: '2/24/1992',
    product_name: 'Y92030',
    payment_method: 'Rhyloo',
    comune: 'Larreynaga',
  },
  {
    order_id: 7,
    order_number: '2370912034',
    person_name: 'Fania',
    email: 'franken6@mit.edu',
    gender: 'Agender',
    payment_date: '6/17/2021',
    order_total: '68',
    persons_amount: 3,
    test_reason: 'Oth incomplete lesion at C8, init',
    booking_date: '3/10/2021',
    booking_time: '2:29 PM',
    id_number: '14892345-L',
    passport: 'WUF142628',
    phone: '8299665702',
    billing_address: '4392 Kim Parkway',
    billing_address2: 'Dahle',
    booking_resource: null,
    birth_date: '6/15/1982',
    product_name: 'S14158A',
    payment_method: 'Latz',
    comune: 'Kosów Lacki',
  },
  {
    order_id: 8,
    order_number: '3516057654',
    person_name: 'Georgy',
    email: 'gkleinsmuntz7@yahoo.com',
    gender: 'Genderfluid',
    payment_date: '9/30/2020',
    order_total: '03460',
    persons_amount: 5,
    test_reason: 'Unsp physeal fracture of lower end radius, unsp arm, sequela',
    booking_date: '9/16/2020',
    booking_time: '11:28 AM',
    id_number: '33685030-F',
    passport: 'AMY793805',
    phone: '3895071558',
    billing_address: '9 Pepper Wood Center',
    billing_address2: 'Longview',
    booking_resource: null,
    birth_date: '10/2/1984',
    product_name: 'S59209S',
    payment_method: 'Divavu',
    comune: 'Januária',
  },
  {
    order_id: 9,
    order_number: '9837464123',
    person_name: 'Carly',
    email: 'cgladdor8@ifeng.com',
    gender: 'Female',
    payment_date: '2/22/2021',
    order_total: '296',
    persons_amount: 4,
    test_reason: 'Nondisp fx of med condyle of r femr, 7thE',
    booking_date: '6/16/2021',
    booking_time: '1:39 PM',
    id_number: '84973638-1',
    passport: null,
    phone: '4421022728',
    billing_address: '998 Erie Avenue',
    billing_address2: 'Sloan',
    booking_resource: null,
    birth_date: '3/16/1995',
    product_name: 'S72434E',
    payment_method: 'Babblestorm',
    comune: 'Tsibulev',
  },
  {
    order_id: 10,
    order_number: '4438011609',
    person_name: 'Ernestine',
    email: 'eordish9@oaic.gov.au',
    gender: 'Genderfluid',
    payment_date: '10/21/2020',
    order_total: '7',
    persons_amount: 1,
    test_reason: 'Chronic dacryocystitis of left lacrimal passage',
    booking_date: '7/14/2021',
    booking_time: '10:50 AM',
    id_number: '53261843-Q',
    passport: 'YUP616586',
    phone: '9044400064',
    billing_address: '09 Dexter Terrace',
    billing_address2: 'Hooker',
    booking_resource: null,
    birth_date: '10/10/1989',
    product_name: 'H04412',
    payment_method: 'Quaxo',
    comune: 'Pengwan',
  },
];

export const cardMocks = [
  { value: 10, title: 'Primer goal', goal: 100 },
  { value: 20000000, title: 'Segundo goal', goal: 40000000 },
  { value: 60, title: 'Tercer goal', goal: 6000 },
];

const today = new Date().toLocaleString();
export const homeRowsMock = [
  {
    date: today,
    fullName: 'Adriana Skep',
    product: 'PCR a domicilio',
    comune: 'Maipu',
    paymentType: 'Paypal',
  },
  {
    date: today,
    fullName: 'Elvina	Mattiussi',
    product: 'PCR en laboratorio',
    comune: 'Providencia',
    paymentType: 'MercadoPago',
  },
  {
    date: today,
    fullName: 'Josselyn	Claire',
    product: 'Test de antigenos',
    comune: 'Las Condes',
    paymentType: 'Khippu',
  },
  {
    date: today,
    fullName: 'Rosamund	Huckstepp',
    product: 'PCR a domicilio',
    comune: 'La Florida',
    paymentType: 'Transferencia',
  },
];

export const homeColumnsMock = [
  {
    Header: 'Fecha',
    accessor: 'date',
  },
  {
    Header: 'Nombre completo',
    accessor: 'fullName',
  },
  {
    Header: 'Producto',
    accessor: 'product',
  },
  {
    Header: 'Sucursal',
    accessor: 'comune',
  },
  {
    Header: 'Tipo de pago',
    accessor: 'paymentType',
  },
];
